livegrep/livegrep

client/test/integration_test.go, client/test/patterns, src/indexer.cc
reported by @shalecraig, this manifests as an incorrect index-key generation for case-insensitive matches again `(scope|permission)`
=> Fix some subtle index key bugs.

server/server.go, server/templates.go, server/templates/templates.go
r? @nelhage 
XML doesn't render properly under html/template, resulting in the `&lt;` at http://livegrep.com/opensearch.xml
Not the cleanest solution, but without pulling in https://github.com/tcard/go-template-interface or similar I don't think we can do much better.
That said, this is my first time writing Go, so :dogscience:
=> Correctly render OpenSearch template

src/codesearch.cc, src/codesearch.h
(1) Use boost::function to simplify the callback function declaration
(2) Allow a filter/transform function to be specified. I have a prototype to look at an index of tags files and then transform the tags match to the actual code match. I can remove this second part if you'd prefer, since it may stay unused if my ctags prototype doesn't make it.
=> Simplified callback declaration and added an optional transform function

client/types.go, server/query.go, server/query_test.go, src/Makefrag, src/codesearch.cc, src/codesearch.h, src/tagsearch.cc, src/tagsearch.h, src/tools/codesearch.cc, src/tools/transport.cc
This addresses what I wanted in #23. 
To use this, you would:
1. Create a tags file with ctags on your source
2. Run codesearch -dump_index on the tags file
3. Run codesearch -load_index and -load_tags, with the tags backend listening on another port
4. Make sure to modify server.json to refer to both backends
The overall algorithm is pretty simple. I use the tags index for searching through lines in the tags file. For each match in the tags file, I transform the match by using the source index to get the context lines.
There are still some rough spots, such as lack of documentation on setting this up, or the fact that you need to ensure that the tags file would have the same path as the path stored in the index file. However, I find that this is actually quite useful in finding …
=> Added support for searching through ctags results

server/query.go, server/query_test.go
And add a test.
should fix the regression from #28
=> Fix `lit:` (regressed in previous commit)

WORKSPACE
Due to a regression in gcc 6.1 re2 failed to build at one point. Here's an issue describing the problem: https://github.com/google/re2/issues/102
I've updated the reference to the commit which includes the workaround. I haven't investigated what else changed between the two versions but I can if you'd like. If you'd rather see it use an even newer version of re2 I could also investigate that.
Fixes:
```
jacob:shell:master:~/src/third_party/livegrep
$ bazel build //...
INFO: Found 40 targets...
ERROR: /home/jacob/.cache/bazel/_bazel_jacob/0e3155d251e04ba4aa26ee3b6c5c65f1/external/com_googlesource_code_re2/BUILD:11:1: C++ compilation of rule '@com_googlesource_code_re2//:re2' failed: linux-sandbox failed: error executing command /home/jacob/.cache/bazel/_bazel_jacob/0e3155d251e04ba4aa26ee3b6 …
```
=> Update to a version of re2 which includes a workaround for a bug in gcc 6.1

src/lib/radix_sort.h
I'm guessing this is a platform difference between us; perhaps this is included implicitly by your `algorithm` header?
Fixes:
```
jacob:shell:master:~/src/third_party/livegrep
$ bazel build //...
INFO: Found 40 targets...
ERROR: /home/jacob/src/third_party/livegrep/src/BUILD:1:1: C++ compilation of rule '//src:codesearch' failed: linux-sandbox failed: error executing command /home/jacob/.cache/bazel/_bazel_jacob/0e3155d251e04ba4aa26ee3b6c5c65f1/execroot/livegrep/_bin/linux-sandbox ... (remaining 252 argument(s) skipped).
In file included from src/chunk.cc:8:0:
./src/lib/radix_sort.h:13:21: error: variable or field 'lsd_radix_sort' declared void
void lsd_radix_sort(uint32_t *left, uint32_t *right);
^~~~~~~~
./src/lib/radix_sort.h:13:21: error: 'uint32_t' was not declared in this scope …
```
=> Add include for cstdint for uint32_t

src/tools/BUILD
Fixes:
```
jacob:shell:master:~/src/third_party/livegrep
$ bazel build //...
INFO: Found 40 targets...
ERROR: /home/jacob/src/third_party/livegrep/src/tools/BUILD:1:1: C++ compilation of rule '//src/tools:grpc_server' failed: linux-sandbox failed: error executing command /home/jacob/.cache/bazel/_bazel_jacob/0e3155d251e04ba4aa26ee3b6c5c65f1/execroot/livegrep/_bin/linux-sandbox ... (remaining 283 argument(s) skipped).
src/tools/grpc_server.cc:17:26: fatal error: boost/bind.hpp: No such file or directory
#include <boost/bind.hpp>
^
compilation terminated.
INFO: Elapsed time: 17.760s, Critical Path: 17.30s
```
=> Add dep for @boost//:bind to grpc_server

README.md
Perhaps the -listen option and relevant code should be removed from the source in a different commit?
=> Update readme to use grpc, as the frontend no longer works with the legacy method

server/server.go
I've noticed that if you have multiple backends, then the "default" backend used by the /search/ page is not deterministic. This can be confusing to users.
=> Return backends in the order specified in the config file

cmd/livegrep-github-reindex/main.go
Tested and live now in Stripe's QA env.
=> Render GitHub links correctly for any GitHub origin

src/indexer.cc
The variable length array failed to compile on my computer because we
were using an `intrusive_ptr`. Switching to `std::vector` fixed it.
Fixes #42
=> Fix compilation error.

README.md
-index_only is necessary to not start the server immediately after https://github.com/livegrep/livegrep/commit/5ae320758df37c8511d0f3867418bf1762494d74
=> Update README example to use -index_only option

src/git_indexer.cc
This fixes ("works for me") issue #46.
No regression test is included. I started writing a higher level test that would call `build_index()` or `git_indexer`'s `walk()` against `doc/example/index.json` (and other example json files), but got bogged down in not knowing how to bazel.
Thank you for maintaining livegrep!
=> indexer: check whether ref resolved to commit

cmd/livegrep-fetch-reindex/BUILD, cmd/livegrep-fetch-reindex/main.go
Inspired by `livegrep-github-reindex`, this clones/fetches a number of
git repositories in parallel and then regenerates the index. Repository
information is provided in the index json config format used by
`codesearch`, with a `remote` field in the `metadata` dictionary
indicating where to fetch the repository from.
The code is almost entirely plagiarized from `livegrep-github-reindex`.
`livegrep-github-index` itself could probably be refactored to generate
an index config with `remote` fields and then invoke this.
=> Add livegrep-fetch-reindex helper command

web/htdocs/assets/css/codesearch.css, web/htdocs/assets/js/codesearch_ui.js
This was originally authored by @christoffer on an old fork of livegrep; I've taken his code, dropped it onto the modern livegrep mainline, and lightly tweaked a few things.
This is a significant change to the search result UI, so I recommend playing with it a bit to see how you like it. I think the most notable change in terms of user interaction is that the click-through link is the result snippet itself, rather than the header with repo/filename, so it's now impossible to copy text directly from the result snippet.
=> Group multiple search results within a file

src/chunk.h, src/chunk_allocator.h, src/codesearch.h
Some of these are reasonably obvious, but some are a bit subtle. I
thought it would be helpful to record the understanding I've extracted
from the code (and be corrected if my understanding is wrong!).
It seemed particularly useful to note the effective lifetimes of the
things which are only used during index construction. (It might further
be useful to factor those out into separate builder classes of some
sort.)
=> Add explanatory comments to object & struct fields

server/backend.go, server/server.go, src/codesearch.cc, src/codesearch.h, src/dump_load.cc, src/proto/livegrep.proto, src/tools/grpc_server.cc
- Create a /debug/stats route
- Include index creation time in Info RPC result
- Report index age as a stat
It's not clear whether this is the right long-term approach for stats (maybe we'd rather speak statsd or something?).
=> Add rudimentary stats reporting

server/api.go, server/api/types.go, src/codesearch.cc, src/codesearch.h, src/dump_load.cc, src/proto/livegrep.proto, src/tools/codesearch.cc, src/tools/grpc_server.cc, test/codesearch_test.cc, web/htdocs/assets/css/codesearch.css, web/htdocs/assets/js/codesearch.js, web/htdocs/assets/js/codesearch_ui.js
Run the input query against file paths as well as file contents, and show matches before the main results.
The filename index isn't stored in the on-disk format, but only held in memory, and rebuilt every time the index is loaded. On our corpus this adds about 2.5s of startup time.
I'm not totally happy with the code quality (copied JS; crudely refactored suffix_search function) or the UX (probably want a shorter list of filename results and some heuristics on whether they're interesting to display), but it's a start!
Fixes #17.
=> Integrated file search

web/htdocs/assets/css/codesearch.css
Currently, the '\<a\>' tag takes up the entire length of the header div.
This means that you can't highlight the file path if you click down
and drag left to highlight the path from the right.
This change makes the <a> tag take up only the minimum width needed,
allowing highlighting to work as expected. The background color
change is done to merge the two backgrounds and produce the same
color as before.
=> Minor css change to allow users to highlight the file path more easily.

web/htdocs/assets/css/codesearch.css, web/htdocs/assets/js/fileview.js, web/templates/fileview.html
- Clarify that the search action performs a new search; drop modal
search input in favor of sending people directly to the main search
UI.
- Clarify where the view link leads.
- Provide more prominent keyboard shortcut hints.
=> Usability improvements for file viewer actions

web/htdocs/assets/js/codesearch_ui.js
This matches the behaviour for file-content results.
=> Link filename matches to built-in code browser when enabled

web/htdocs/assets/css/codesearch.css, web/templates/index.html, web/templates/layout.html
Since the tech-demo-style header from livegrep.com don't necessarily make sense for a corporate internal instance.
=> If custom header content is provided, replace the default header

web/templates/index.html
I accidentally dropped this in #79. Fixes #84.
=> Restore hidden backend select input

web/htdocs/assets/js/fileview.js
Beginning a new search by clicking the link shouldn't prefill the query `[object Object]`.
In #81 I either broke this or failed to fix it.
=> Bugfix for 'new search' link in file browser

web/htdocs/assets/css/codesearch.css, web/htdocs/assets/js/codesearch_ui.js, web/templates/index.html
=> Drop search permalink

src/codesearch.cc, web/htdocs/assets/js/codesearch_ui.js, web/templates/index.html
- If `max_matches:` is provided in the query, use that as the limit,
regardless of a limit passed on the `codesearch` command line. This
is on the theory that, if the user provides a `max_matches` value
greater than the configured limit, it's because they want to see more
results. If they want to see a LOT of results and are willing to wait
for it, that's their choice.
- Any time the search completes early (without an exhaustive list of
results), indicate that the count in the UI is not exact. Included in
this change because we're making it easier to hit the time limit
(rather than the match limit).
- Mention `max_matches:` in the help section.
=> Tweak max_matches behaviour

web/htdocs/assets/js/fileview.js, web/templates/fileview.html
This is meant to smooth the flow where a user wants to trace multiple
layers of a call stack, and then switch back and forth between
inspecting the function bodies.
The change will be a bit disruptive for users accustomed to "enter"
performing a search in the current tab; hopefully it shouldn't be too
hard for them to switch to "/".
=> From file view, "enter" opens search in new tab

server/api.go, server/api/types.go, web/htdocs/assets/js/codesearch.js, web/htdocs/assets/js/codesearch_ui.js
Tell the frontend explicitly whether a search was filename-only or not;
if it was, render more results, and show the number of file results in
the UI.
=> Make frontend smarter about filename-only searches

server/backend.go, server/server.go
Previously, the healthcheck represented only the `livegrep` ability to
respond to requests. This extends the healthcheck to verify that
`livegrep` has ever been able to talk to all of its backends.
=> Improve healthcheck slightly

web/htdocs/assets/css/codesearch.css, web/templates/layout.html
- Use `"Menlo", "Consolas", "Monaco", monospace` as fonts for source
code and paths.
- Change match highlight color, so it's distinguishable from
typical browser search-in-page highlighting.
- In the file-viewer, change highlight.js style to googlecode, and tweak
line-height for slightly denser display.
=> Text style refresh

src/chunk.cc, src/chunk.h, src/codesearch.cc, src/dump_load.cc
When indexing, codesearch builds chunks in the order that repositories
are listed in the configuration. When searching, it examines chunks in
the same order. This means that it finds results from repos in roughly
the order repos listed in the configuration (modulo multiple threads
concurrently processing chunks).
Since repo_pat constraints are applied after the main suffix array
search, this means that the search may examine and discard many
candidate lines before it ever reaches the desired repo, which can take
a long time. On our instance (17 repos, ~11GB index), restricting a
search like "e" to the last repo takes 6-7x as long as the same search
restricted to the first repo.
This change allows us to skip irrelevant chunks entirely. However,
the improvement in overall search performance …
=> Skip chunks that don't contain desired repos

server/BUILD, server/server.go, server/templates.go, server/templates/templates.go, web/BUILD, web/templates/layout.html
This ensures that users don't see old cached versions of the javascript.
Enforcing subresource integrity here is probably unneeded, but we have
the information, so why not?
=> Fetch static resources with content hashes

web/src/codesearch/codesearch_ui.js, web/templates/layout.html, web/webpack.config.js
Behaviour is as follows:
- Any time you modify one of the query controls in the UI, your modification is stored in a cookie.
- If you navigate to the blank livegrep search page, the control settings are loaded from your cookie, falling back to defaults for any controls you've never explicitly set.
- If you navigate to a livegrep search with a query already provided, the control settings are loaded from the URL and your preferences are ignored. This way, links to search results are stable (modulo changes to the underlying index, of course).
This doesn't make the "case" control sticky because I believe "auto" really is what the user wants 99% of the time.
Fixes #60 by addressing this portion of the issue:
> Crucially, if the last time you used that other tool you searched repository X, then …
=> Make regex, repo, and context controls sticky

test/BUILD
A bare `test_suite()` target automatically includes all tests in its `BUILD` file, allowing the tests to be run without needing to type their names.
=> Add `test` target so `bazel test //test` works

web/src/codesearch/codesearch_ui.js
If we don't provide an expiration, this sets a session cookie. But we'd
like preferences to be more persistant than that. js-cookie interprets
the `expires` argument as days until expiry; 100 years should be plenty.
=> Store prefs in a long-lived cookie

server/api.go, server/query.go, server/query_test.go
This makes the parsing more intuitive (to me). Some of this might be contentious.
The most fundamental change is that this exposes to the parser whether the query is a regex or not; this information is used to modify parenthesis handling.
The test case changes provide a good summary of the behaviour changes.
=> Query parser tweaks

cmd/livegrep-reload/BUILD, cmd/livegrep-reload/main.go
This stand-alone command supports more complicated workflows than simply running `livegrep-fetch-reindex` and wanting an immediate reload when it finishes (for example, this lets you `livegrep-fetch-reindex`, then build a separate tags index, and only then reload).
=> Add reload

src/tools/codesearch.cc
Several conditionals in `grpc_server.cc` expect the tags `code_searcher`
pointer to be NULL if no tag index has been provided:
```
if (tagdata != nullptr)
response->set_has_tags(tagdata_ != nullptr);
if (tagdata_ == NULL)
```
But, alas, the initialization routine always creates a tags searcher.
Even worse, it leaves it un-finalized if no tags index was provided.
Among other things, this crashes codesearch if `tags:...` is specified
but no tags index has been provided.  And with the debut of our new
tags-first search logic, it also makes the service crash for normal
searches (!) if no tags index is available.  So here we pivot to the
behavior the server code expects: a NULL pointer if no tags index is
loaded.
=> Bugfix: without a tags index, build no searcher

web/src/codesearch/codesearch_ui.js, web/src/fileview/fileview.js
One of our file viewing applications would return 404 on URLs with a
double slash in them, so this helps the js code avoid building them.
=> Avoid double slashes in file viewer URLs

src/dump_load.cc
The daemon is failing on some servers because these calls return 0,
perhaps because stdin has been closed during daemonization.
These asserts should accept all valid fd numbers, including zero.
=> Fix checks of calls returning a file descriptor

WORKSPACE, server/api.go
This gives us https://github.com/bazelbuild/rules_go/pull/1054 which
restores to rules_go the ability to fetch Go packages with git through
an HTTP/HTTPS proxy.
=> Fix HTTP[S]_PROXY by upgrading rules_go to 0.7.1

src/dump_load.cc
The error message that the assert was printing is somewhat opaque, and
did not record which file could not be opened:
```
codesearch: src/dump_load.cc:361: load_allocator::load_allocator(code_searcher*, const string&): Assertion `fd_ > 0' failed.
```
=> Print error and exit if index cannot be opened

cmd/livegrep-reload/main.go
Otherwise, the command enters a loop trying forever to connect.
=> Have livegrep-reload exit if server unreachable

server/api.go, server/api/types.go
This allows parsing the logs to get a close approximation of the time the end-user waited for a response.
=> Add a "total wallclock time" calculated from livegrep

web/htdocs/assets/css/codesearch.css, web/src/codesearch/codesearch_ui.js
A popular request from users: buttons that automatically narrow the
current search to files matching a single extension.  The extensions
offered are all culled from the currently displayed files.
Because these buttons need to advance the search history URL to a new
state from which the user often wants to return by hitting Back, this
diff also fixes livegrep's previous problem of not preserving browser
URL history; we now create a browser history state for each search
that successfully returns and is drawn on the screen.
=> Add buttons to narrow results by file extensions

src/tools/codesearch.cc
Otherwise, a server run with `-load_tags` will leak a memory map to its
tags index every time it reloads, potentially keeping old index files
alive instead of letting the filesystem remove them.
=> Free tags code_searcher before creating a new one

web/BUILD
Newer bazel uses `bazel-out/k8-fastbuild/bin/` -- use $BINDIR to be
both forward and backward compatible.
=> Switch to the more portable $BINDIR when using sed in genrule

src/codesearch.cc, test/codesearch_test.cc
This fixes backend crashes when the filename search needs to look
up a match in the last index.
=> Fix an incorrect assert in filename_searcher.

web/src/codesearch/codesearch_ui.js
Users have complained that, following my `1705f305c15c` contribution,
Livegrep is now a bit aggressive about spamming their browser history —
in cases where searches return quickly, every single character they type
creates a new history item that they have to slog "Back" through if they
want to return to the previous page.  So let’s back off and not create
new history items while they’re clearly in the middle of typing.
=> Avoid spamming browser history with each keystroke

src/codesearch.cc, src/codesearch.h, src/proto/go_proto, src/tagsearch.cc, src/tools/grpc_server.cc, test/BUILD, test/tagsearch_test.cc, web/src/codesearch/codesearch_ui.js
On the assumption that tagged lines have greater semantic weight than
other lines that match the user’s search, let’s power a search by
consulting the tags index first then falling back to the main index.
=> If a tag index is provided, search it first

web/src/codesearch/codesearch.js
Previously we were only displaying errors only for 400-series responses,
which leaves users waiting forever if other errors are encountered.
=> Display error if server is unreachable or 500s

server/fileview.go, web/src/fileview/fileview.js, web/templates/fileview.html
Many of our users asked us to better expose the support that the
Livegrep file browser offers for permalinks to exact revisions of a
particular file, so let’s add links between HEAD and the permalink.
=> Add [y] shortcut to create permalink

.gitignore, doc/examples/livegrep/generate_ordered_contents.sh, doc/examples/livegrep/index_with_ordered_contents.json, doc/examples/livegrep/ordered-contents.txt, src/fs_indexer.cc, src/fs_indexer.h, src/tools/codesearch.cc, src/tools/transport.cc, src/tools/transport.h
This lets codesearch produce an index that has been populated in a specific order to position more interesting files first, or to exclude uninteresting files entirely.
I decided to go with this approach rather than implementing ranking inside of livegrep because it gives the user the flexibility to write arbitrarily complicated filtering/ranking logic while keeping livegrep generic.
=> Add support for walking a custom-ordered subset of filesystem paths

web/src/fileview/fileview.js
Without this check, attempts to perform certain Ctrl+[KEY] browser
operations will also annoyingly launch one of our file view shortcuts.
=> Check Ctrl/Alt/Shift detecting file view shortcut

web/src/codesearch/codesearch_ui.js
When the user arrives at `/search/?q=` they are usually redirected
immediately to a more detailed URL, which shouldn’t get its own entry in
the browser history or else they will have to press “Back” twice to see
the page they were on before being sent to Livegrep.
=> Don't pushState on initial navigation (#7)

server/fileview.go
The previous URL for the “return to HEAD” link didn’t work for
directories, since their URL ends with “/” rather than their name.
=> Fix relative link so it stays at directory

web/src/fileview/fileview.js
Users familiar with other file viewers asked that when text is selected,
“N” and “P” move to the next and previous instance of that text.
=> Create next/previous selected work shortcut

web/src/fileview/fileview.js, web/templates/fileview.html
When the user highlights text in the file view, update the help atop the
page to make explicit that “/” now searches for the selected text.
=> Better help text when a selection is selected

web/htdocs/assets/css/codesearch.css, web/src/fileview/fileview.js, web/templates/fileview.html
This updates both the “help” popup as well as the help text across the
top of the file view header so that both match the complete list of new
text searching and selection features.  It also improves the markup and
CSS used to display the help popup with better tag semantics (“kbd”) and
visual display (lines are now uniformly spaced instead of having odd gaps).
=> Update “help” texts with recent file view features

web/src/fileview/fileview.js
If we ignore all keystrokes when “Shift” is pressed, then users can’t
type “?” and have its shortcut fire.
=> Fix broken `?` shortcut for help in file view

web/templates/index.html
Our users were confused about why we advertise “file:” when the engine
also supports “path:”. They always think there must be an interesting
difference between the two. So let’s only advertise the modern one.
=> Remove deprecated “file:” from hints on front page

web/htdocs/assets/css/codesearch.css, web/templates/fileview.html
A very generic CSS class name (“code”) was used in the file viewer to
position the pane of source code absolutely at the top of the page.
Alas, “code” is also used as a CSS class when prism.js is highlighting a
code snippet inside of Markdown.  So let’s fix the collision.
=> Fix Markdown code snippets piled at top of page

web/templates/layout.html
There’s another <link> to it 9 lines above this, and the other one
is nicer: it includes the asset hash.
=> Remove duplicate <link> to “codesearch.css”

server/server.go, server/templates.go, web/templates/layout.html
Here at Dropbox we’ll be using a nonce to protect each bare `<script>`
tag, and this code makes it easy for third parties to add nonces without
editing the code in too many places.
=> Add “ScriptNonce” that adds attribute to scripts

server/server.go, server/templates/templates.go, web/templates/common/layout.html, web/templates/fileview.html
It turns out?  Our CSP wants nonces on *every* script and link tag, not
just inline scripts.  Thanks to the recent template simplification, it’s
now easy to use the Nonce both up in the main “layout.html” template and
also down in specific templates like “fileview.html”.
This also simplifies the code by precomputing the full text of the HTML
attribute, so that the templates needn’t be festooned with “if” statements.
=> Fix nonces by adding them to all script, link tags

server/BUILD, server/server.go, server/server_test.go
At the moment we can't use the internal file viewer because it has the assumption that repository names cannot contain forward slashes.
This isn't true of GitHub repositories ("livegrep/livegrep"), so to make the internal viewer work for repositories containing slashes it seems like the easiest thing to do is replace the route parsing logic with our own.
We do this by building a regular expression which can match on any of the configured repositories followed by a `/` and the path. I haven't thought too much about the performance implications of the regular expression with a sufficiently large number of repositories, so open to doing the matching differently.
=>  Fix internal file viewer for repository names containing '/' character

src/tagsearch.cc, test/tagsearch_test.cc
An interior “|” inside either the main pattern or the file path pattern
would cause the tags-based search to match many lines it should not,
since the subordinate patterns were being combined into a single pattern
without parens around the subordinate patterns.
=> Prevent “|” from breaking tags-based searches

src/codesearch.cc, test/codesearch_test.cc
Users reported that as the filename list grew small, they often would be
given the same filename twice. After reproducing the situation by hand,
I discovered the filename matcher needed to be careful about not
returning the same name twice in a row.
=> Stop filename match from returning same name twice

server/config/config.go, server/server.go, web/htdocs/assets/css/codesearch.css, web/src/codesearch/codesearch_ui.js
This can be used to, for example, add links to open an editor such as "Open in VS Code" or web tools, etc.
Sample `livegrep.json` snippet:
```
"file_links": [
{
"label": "Open on GitHub (file only)",
"url-pattern": "https://github.com/{name}/blob/master/src/{path}",
"whitelist-repo-pattern": "^([^/]+/)?livegrep$"
},
{
"label": "Open on GitHub (with line)",
"url-pattern": "https://github.com/{name}/blob/master/src/{path}#L{lno}",
"whitelist-repo-pattern": "^[^/]+/livegrep$"
}		
]
```
Check the following `livegrep.json` configurations:
- No `file_links` key works fine
- An empty `file_links` array works fine
- A link with empty `whitelist-repo-pattern` is shown for all repos
- Links are only shown for repos that match the regex in `whitelist-repo-pattern`
Check this functionality in the UI: …
=> Add configurable links to files and lines

cmd/livegrep/livegrep.go
This allows a user to specify the backend address for codesearch when running livegrep by passing a `-connect` flag. It uses the current configuration as a default, so it won't break existing configurations.
=> Allow backend address to be configurable for livegrep

.circleci/Dockerfile, .circleci/build.sh
Companion to #204. cc @miikka
This updates the Docker image used by CircleCI to use a newer version
of Bazel (0.21.0). It also adds a few flags to the bazel commands in
the CircleCI build script to account for deprecated usage in some
dependencies.
This build itself won't be using the new image. We'll need to build and push the new image, then update the tag in the `.circleci/config.yml` file.
=> Update CircleCI builds

BUILD, WORKSPACE
Hi, I'm trying to try out livegrep! To build livegrep with Bazel 0.21 on macOS, I had to bump a number of rule dependencies – see the attached patch. In addition to that, I had to use the workaround in https://github.com/livegrep/livegrep/issues/120#issuecomment-337635796 and run Bazel with `--incompatible_package_name_is_a_function=false` due to use of deprecated variables by rules_node (patch at https://github.com/dropbox/rules_node/pull/14).
=> Bump deps to build with Bazel 0.21

.bazelrc, WORKSPACE, src/proto/BUILD, src/tools/BUILD
This will fix the need for `--incompatible-*` options in .bazelrc. Also, `pubref/rules_protobuf` is deprecated so we need to upgrade anyways.
Not yet passing tests.
cc @miikka
=> Switch to the new protobuf rules

web/src/fileview/fileview.js
When linking to a range in GitHub, the syntax is #L43-L70. With livegrep,
the syntax is #L43-70. This inconsistency causes me to make a lot of
mistakes.
This patch makes the fileview frontend accept both anchor styles for
linking to line ranges.
cc @nelhage
=> Allow GitHub-style line range anchors

server/config/config.go, src/git_indexer.cc, src/git_indexer.h, src/proto/config.proto, src/tools/codesearch.cc
The flag, when set to true, will treat submodules as though they
are just regular files inside the parent repo. The submodule is
indexed at the revision that the parent repo points to.
Fixes livegrep/livegrep#216
=> Add a flag to include submodules when walking the tree.

src/content.cc
file_contents_builder::build was unconditionally constructing a file_contents object over the result of the allocator. If the allocator returned nullptr, undefined behavior happened. Move the nullptr check earlier to fix this.
=> Avoid undefined behavior in file_contents_builder::build.

WORKSPACE
Hi! Without these bumps I wasn't able to build livegrep with bazel 0.25.1, so here's a PR.
=> Bump rules_proto and bazel-compilation-database for bazel compatibility

src/codesearch.cc, src/codesearch.h, src/proto/livegrep.proto, src/tagsearch.cc, src/tools/grpc_server.cc
This change allows customizing the number of context lines returned on a per-request basis. It involves the following patches:
- Additional field in the search request proto definition for the client to specify the number of context lines
- Additional `codesearch` runtime flag to set the default number of context lines if not specified in the request (defaulted to `3` so to not change existing behavior)
- Augment the `query` struct with `context_lines` to store this value, to be accessed in main search logic where `kContextLines` was previously read
This should be a non-breaking change for the first-party livegrep UI since the "Context" on/off checkbox operates only at the UI layer (by simply choosing not to render the before/after context).
Please feel free to close this PR if this isn't …
=> Ability to set number of context lines per request

cmd/livegrep-github-reindex/main.go
This reverts commit ee04aebd09c7847c1aae4eb6b086ace9f91affe3.
fixes #237 (although we should really add tests)
regresses #220, but the previous fix was kinda wonky anyways, since adding `HEAD` to your fetchspec doesn't actually work quite like I'd thought it did…
=> Revert "livegrep-github-index: Update HEAD as well as other refs"

src/proto/livegrep.proto, src/tools/grpc_server.cc
This change proposes the inclusion of two new fields, `index_name` and `index_time` (the config-specified name of the index and the current index timestamp, respectively) in the `CodeSearchResult` message. Both of these field values are obtained from the existing server implementation's member variables.
This ties a unique index identity with every search result (i.e., a search request + one state of the index can deterministically be transformed into a search result). In our deployment of livegrep, the index file is rolled several times per day, so the same search request can yield a different set of results throughout the day.
Our livegrep client leverages a distributed caching layer that caches search results (keyed by a serialization of the query), and including a unique index …
=> Include unique index identity in search result response

server/query.go, server/query_test.go
Found via
https://livegrep.com/search/linux?q=call_usermodehelper%5B(%5D%20file%3A.c&fold_case=false&regex=true&context=true
returning no results, even though
https://livegrep.com/search/linux?q=call_usermodehelper%5C(%20file%3A.c&fold_case=false&regex=true&context=true
worked fine.
=> Fix some parser bugs around mixing [ and (

src/proto/livegrep.proto, src/tools/grpc_server.cc
I've noticed that multithreaded searches (`--threads` param > 0) over an index with many chunks (built with a small-ish `--chunk_power`) result in inaccurate timings in the returned stats message. I'm guessing this is because the timers are run multiple times, once in each thread, causing the total time to be the sum of all individual latencies. This behavior seems correct from a literal standpoint of what the timers are measuring but also a bit unintuitive.
This change proposes the addition of a field to the stats message for an end-to-end "total" time taken by the search. It is measured at a reasonably high level (implementation of the `search` RPC method) in order to most faithfully capture the total server-side search latency.
=> End-to-end server-side search latency stat

src/tools/grpc_server.cc
This offers a small change to the client API that allows clients to bypass the server-side match-based search limiter.
Proposed behavior: When `max_matches` is specified as 0, we will defer to `FLAGS_max_matches`, which in turn defaults to 50 when not specified. When `max_matches` is specified as any negative integer, we explicitly disable the match limiter (the search itself is still subject to the timeout limiter, if enabled).
This is a deviation from current behavior where a zero or negative value of `max_matches` always defers to `FLAGS_max_matches`.
I believe this PR is the only change needed, since the following logic will ignore the match limit if it is zero-valued:
https://github.com/livegrep/livegrep/blob/beca552bc53f644920d78e64504b2c5a84d952a9/src/codesearch.cc#L140
=> Interface to bypass server-side match limiter per request

cmd/livegrep-github-reindex/main.go, tools/build_defs/go_externals.bzl
`-archived=true` is available if anyone needs the old behavior.
fixes #264
=> Skip archived repositories when indexing.

WORKSPACE
By making shallow clones as directed.
The instructions for absl don't work, I speculate because of some
grafts in that repository's history.
=> Suppress some bazel warnings

cmd/livegrep-github-reindex/main.go
Switches the name of the flag that allows repos to be ignored while indexing to `-ignorelist`. I decided not to put this flag through a deprecation cycle -- let me know if you'd like me to add back the old flag, and have it prompt to switch to the new version.
I didn't see any unit tests for this code, so I tested manually on my development machine.
```
$ bazel-bin/cmd/livegrep-github-reindex/darwin_amd64_stripped/livegrep-github-reindex --org livegrep -codesearch bazel-bin/src/tools/codesearch
Updating livegrep/livegrep
Updating livegrep/livegrep.com
Walking repo_spec name=livegrep/livegrep, path=repos/livegrep/livegrep (including  submodules: false)
walking HEAD... done
Walking repo_spec name=livegrep/livegrep.com, path=repos/livegrep/livegrep.com (including  submodules: false)
walking …
```
=> Switch to ignorelist

server/fileview.go
Hey there! 👋 
We were seeing high latencies (~4s) when viewing files inside a repository with a lot of branches (~14000). This was tracked down to this git show invocation.
As far as I can see, git show is built on top of git log. The git log command iterates over every branch head to gather the information it needs to render the standard git log output even if this information is ultimately discarded before being displayed. The git rev-parse command looks up just the information we need in a constant number of disk accesses.
Before:
```
$ time git -C $REPO show --quiet --format="%H" HEAD
ac00907bc674a675bc0de94ceb467cb884e82795
real  0m4.711s
user  0m4.076s
sys   0m0.256s
```
After:
```
$ time git -C $REPO rev-parse HEAD
ac00907bc674a675bc0de94ceb467cb884e82795
real  0m0.003s
user …
```
=> Improve commit SHA lookup performance

src/lib/BUILD, src/lib/fs.h, src/lib/fs_default.cc, src/lib/fs_linux.cc, src/tools/codesearch.cc
This change proposes a new flag `--hot_index_reload` which uses a similar mechanism as `--reload_rpc` to automatically reload the server when the index file on disk changes, using inotify C APIs. This behavior only applies when the server is started with a prebuilt index file (i.e. `--load_index`) and is incompatible with `--reload_rpc` (so that the shutdown thread only waits on a single blocking operations for restarts). As implemented, the server is restarted by touching, copying, or moving a new index to the path specified by `--load_index`.
Our indexing pipeline builds and deploys a new index file every few hours. This change allows the server to automatically pick up the refreshed index without needing to configure a client to issue a manual reload after the deploy completes. …
=> inotify-based hot index file reloads

WORKSPACE
I've encountered a build error since e719c36f02198d36a65850d5f73ef01ba8e853d8 on Bazel 3.4.1:
```
ERROR: no such package '@com_github_grpc_grpc//bazel': Traceback (most recent call last):
File "/home/kiwi/.cache/bazel/_bazel_kiwi/9737f374979233968789ebadfccef073/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
_clone_or_update(ctx)
File "/home/kiwi/.cache/bazel/_bazel_kiwi/9737f374979233968789ebadfccef073/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
git_repo(ctx, directory)
File "/home/kiwi/.cache/bazel/_bazel_kiwi/9737f374979233968789ebadfccef073/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
_update(ctx, git_repo)
File "/home/kiwi/.cache/bazel/_bazel_kiwi/9737f374979233968789ebadfccef073/external/bazel_to …
```
=> gRPC 1.13.1

WORKSPACE, src/BUILD
GRPC also depends on RE2, by the `com_github_google_re2` name. The
fact that we were using a different name resulted in GRPC pulling in a
second copy. This used to mostly work fine because they were
ABI-compatible, at least in the pieces we use. However, RE2 recently
updated the layout of a core struct in
572d6abf7f227053a4f8b83381fc4378714a2552, which meant that we ended up
seeing one version of the headers and linking against a different
version of the objects, which was a no good bad time.
IMO this is arguably a bug in GRPC's bazel build -- it should not be
leaking those headers -- but this fix is correct in any case.
=> Update the name of the RE2 dependency

src/codesearch.cc, src/dump_load.cc, src/dump_load.h
This change proposal attempts to fix #279. It includes the following high level changes:
- Expand the index header to include sizes and offsets of [all three data structures used to store the filename index](https://github.com/livegrep/livegrep/blob/7b3cccb9c9e6201fb309f72fc4d580807e65bd12/src/codesearch.h#L231)
- Encode said data structures into the dump in a new routine `dump_filename_index` in `codesearch_index`, and decode their contents into a `code_searcher` instance on a `load_index` operation
- Bump the index version constant due to a backwards-incompatibile index file format change
- Remove the `index_filenames()` step invoked when loading an offline-built index file
This seems to work in my very limited manual testing. For an index with ~75M lines of source code over ~300K …
=> Encode filename index in index file dump

src/tools/codesearch.cc
If the repo being indexed has files that are too large, a WARN
line is emitted between the "walking HEAD..." and "done" outputs.
This results in messy stderr that looks like this:
walking HEAD... WARN: file is too big to be indexed
WARN: file2 is too big to be indexed
done
Apart from looking messy, this makes it harder to autodetect
warnings with grep. It seems better to insert a newline
after the "walking HEAD..." output, which also makes it
consistent with the other branch of code immediately above.
=> Avoid messy stderr output in some cases

web/src/codesearch/codesearch_ui.js
Let's say you do a search for "foo" and it results in:
```
src/path/file.foo
src/bar.cpp: "foo"
```
The current code will only add `.cpp` to the common extension list from `bar.cpp`, despite `file.foo` also showing up in the file path results.
This PR fixes that by considering file paths for the extension list.
=> fix bug where file extensions weren't counted for path only results

server/fileview.go
Adding `BUILD.bazel` and `.sky` (for Starlark files) to use python-ish highlighting too.
Thoughts on adding a config section so this doesn't need to be a code change?
=> Add some more python-ish files to syntax highlighting

web/htdocs/assets/css/codesearch.css, web/src/codesearch/codesearch_ui.js
On the search results page, one thing I've noticed is that copying the path from the header results in a `^M` newline character being copied as well.
One way to reproduce this is to start a search, then click and drag your mouse starting where the red arrow is (e.g., to select the text `web/src/codesearch/codesearch_ui.js`)
When you paste, it also pastes a newline. This adds another step to delete the newline if you're opening a file by pasting the path into something like vim's `:e` command.
To fix, I wrapped the `<a>` in big span. It's bigger than the link, so only the text remains the target, but you can still highlight and not get the newline. No visual differences detected.
Before:
After:
=> Add a max-width span around file name link

web/src/codesearch/codesearch_ui.js
Fixes bug #305, which was introduced in #303. 
This time I got the right version of bazel and tested it locally all the way. Sorry. The second argument to `h.span` needs to be an array, even if there is only one element as children.
=> Fix path names

cmd/livegrep-github-reindex/main.go
~~Small change to allow the number of repos per GitHub api request to be configurable. I mention the max is 100, but don't do any validation because the GH REST api does it. `go-github` doesn't validate this either, as far as I [can tell](https://github.com/google/go-github/blob/85425ec5f1e4118be4b578e5b6ad07f9ea32cf5f/github/repos.go#L283).  This is change 2 from issue #313~~
PR now simply bumps the PerPage number to `100`, which is the max allowed by the github REST api. Should have no effect on users/orgs that have less than 100  repos, while always reducing the num of network calls made for those that have >= 100 repos.
=> bump PerPage value for gh-reindexer repo fetching to max

cmd/livegrep-fetch-reindex/main.go, cmd/livegrep-github-reindex/main.go
This change does two things:
1. allows `livegrep-github-reindex` to make requests for repos (per user or per org) concurrently at a specified limit. By default it's set to 1, which retains the current behavior wherein only 1 call pero user/org is made at a time. Settings the limit to ~40 for me dropped the time the `updating repos` step took from ~1min to ~5s when indexing 2 orgs with a combined ~4k repos.
2. adds a new flag, `num-workers` to `livegrep-fetch-reindex` that updates the number of workers used to run the `checkoutRepos` function. Also updates `livegrep-github-reindex` and adds the arg `num-repo-update-workers` whose value will be bassed to the call to `livegrep-fetch-reindex` as `num-workers`
For the concurrent requests, I made the decision to try to retain order (the results …
=> Concurrent reindexer GitHub requests

cmd/livegrep-github-reindex/main.go
This PR adds a flag to skip indexing in `cmd/livegrep-github-reindex/main.go`. At Stripe we use livegrep over a couple instances of GitHub, so our re-index operation calls this command a few times, combines the index, and generates the final index. This means that we are indexing `n + 1` times (where n is the number of GitHub locations) but only the last one matters.
This PR adds an easy option to simply return after indexing.
=> Add option for noindex to livegrep-github-reindex

server/fileview.go
This should let https://cdnjs.cloudflare.com/ajax/libs/prism/1.14.0/components/prism-typescript.min.js autoload for `.ts` files.
Some day I'll get around to a PR for the config options for this list, like I mentioned in #300 😅
=> Add typescript highlighting for .ts files

src/tools/codesearch.cc
This change proposes the addition of command line flags to `codesearch` to control the maximum receive/send message sizes used by the gRPC server. The two new flags are `--max_recv_message_size` and `--max_send_message_size`, which accept int32s as values.
The immediate motivation is to allow for very large query results that would otherwise exhaust the gRPC-default max outbound message size of 4 MB. It can also be used to set more aggressive circuit breakers than the gRPC defaults.
Verification of an overridden send threshold:
```bash
$ ./bazel-bin/src/tools/codesearch --load_index /tmp/index --grpc localhost:9999 --timeout 300000 --max_recv_message_size 4
```
```
Received message larger than max (15 vs. 4)
```
Verification of an overridden receive threshold:
```bash
$ …
```
=> Flags to control gRPC server max send and receive message sizes

cmd/livegrep-fetch-reindex/main.go, cmd/livegrep-github-reindex/main.go
The original PR implemted the logic in github-reindex not realizing that the fetching of the repos was tightly
coupled to fetch-reindex. This means that, with the old implementation, you could run the config generation but nothing
would actually update. You would just have HEAD but the repos would still be outdated.
Ideally we could de-couple github operations from indexing operations and independently fetch/index, but saving a full refactor
the easiest solution is to pass the flag into fetch-reindex and exit after fetching repos
=> Move core logic of no-index to fetch-reindex

docker/base/Dockerfile
Sorry I missed this! 
The extra `}` that snuck in was creating a seperate directory, like
```
livegrep/...
livegrep}/nginx.conf
```
So when nginx tried to start up with livegrep/nginx.conf it failed.
=> fix path for nginx conf in Docker image

server/BUILD, server/fileview.go, server/fileview_test.go, web/htdocs/assets/css/codesearch.css, web/templates/common/filecontent.html, web/templates/fileview.html
Small change to automatically show README file's next to the directory viewer, if they exist. 
Decided to have this happen for any directory, in case a repo has README files in subdirectories. I restricted the possible readme extensions to the set that GitHub accepts (https://github.com/github/markup), which may not be necessary but eh.
Here's what this looks like when a readme file is present. 
And if no readme file it looks the same as before.
=> Show README file next to directory viewer

src/lib/fs_linux.cc
While working on the unrelated patch described https://github.com/livegrep/livegrep/issues/331#issuecomment-1101043856 I found a stack overflow bug in the inotify-based index reload watcher.
A `read` on the inotify fd returns a `struct inotify_event`, plus the name of the affected file, followed by a null termination character. The previous logic allowed a full read of all this data, but into only a container of size `struct inotify_event`. This change allocates a buffer with the maximum possible read length to avoid stack corruption.
To reproduce:
Build an index `/tmp/index`, and load it with:
```
$ ./bazel-bin/src/tools/codesearch --load_index /tmp/index --hot_index_reload
```
```
$ touch /tmp/index
```
Observe stack overflow:
```
Serving...
*** stack smashing detected ***: terminated …
```
=> Fix stack overflow in inotify-based reload watcher routine

cmd/livegrep-fetch-reindex/BUILD, cmd/livegrep-fetch-reindex/main.go, cmd/livegrep-github-reindex/main.go, tools/build_defs/go_externals.bzl
Hello - this patch attempts to solve sync issues between the mirrored clones that `livegrep-github-reindex` creates and their upstream counterparts - described in #293. TLDR of that issue is that when changes are made to the HEAD refs of the remotes of locally cloned mirror repos,  `git fetch -p` will invalidate the current local HEAD, but won't update it to match the new remote HEAD, which  eventually leads livegrep to think that repo is empty when it's indexing, which causes it to be skipped.
To fix this, we make an extra call to git - `git ls-remote --symref origin HEAD`. We then compare the remote `HEAD` information to the local `HEAD`, and if different, then we manually update with `git symbolic-ref HEAD {newHead}`.
Even with the extra call to git, this patch doesn't slow down …
=> Update mirrored git clones when remote HEAD changes

cmd/livegrep-fetch-reindex/main.go
This should fix the issue @juliannadeau-stripe was seeing in their deployment with empty repos causing a crash. I've been running this patch on our deployment which has plenty of empty git repos and no failures so far. 
These are two commits I missed in prepping #340 for upstream, as mentioned in #341.
Proof of fix. Before:
```
$ main
$ ./bazel-bin/cmd/livegrep-fetch-reindex/livegrep-fetch-reindex_/livegrep-fetch-reindex -num-workers=60 -out=xvandish.idx ../repos-for-livegrep/xvandish.json
Updating xvandish/aws-go-photo-resize-lambda
Updating xvandish/dotfiles
Updating xvandish/livegrep
Updating xvandish/aws-node-photo-resize-lambda
Updating xvandish/livegrep-fragment
Updating xvandish/livegrep.com
Updating xvandish/my-empty-repo
Updating xvandish/aws-node-photo-delete-lambda
panic: …
```
=> Update head ref patches

README.md, server/api.go, server/server.go, web/src/codesearch/codesearch.js
With GET, the `repos` parameter may grow the URL beyond the maximum
length permitted by the server.
Use POST instead.
Fixes #259.
Also, improve the bazel installation instructions in the README.
=> Make /search API requests with POST

tools/org_dropbox_rules_node/node/defs.bzl, tools/org_dropbox_rules_node/node/tools/npm/utils.py, web/BUILD
I'm hoping `/usr/bin/env python3` is a safe assumption to make in 2022: modern macOS doesn't have `python` present.
On arm64 Macs, the host component of the bindir is `darwin_arm64`. This breaks the `sed` command in the `genrule` creating `hashes.txt`, which used `_` as the delimiter. We can switch it to whatever won't be in that path.
Also, throwing this in the same PR, but open to separating it out:
We do a bizarre workaround to set `HTTP_PROXY` with `--define` flags -- instead, we should let Bazel forward the value from the environment with `--host_action_env` if it's needed. Consequently, we _shouldn't_ pass `env` when `use_default_shell_env = True` because those values are entirely ignored: https://github.com/bazelbuild/bazel/issues/5980.
=> Fix up Bazel config for http_proxy forwarding and supporting darwin_arm64

doc/examples/livegrep/index.json
When not using the file viewer, metadata.github takes precedence over
metadata.url_pattern.  When using the file viewer, only url_pattern is
consulted.  url_pattern is incorrect for this repository.  Fix it.
=> Fix example url_pattern

web/htdocs/assets/css/codesearch.css
Use CSS media queries to define custom properties ('variables') for the colors used throughout the livegrep UI. There were _quite a few_ colors used previously, so even in the light mode variant this is a little bit different from the current CSS. I simplified some colors to be the same, rather than the slight differences they had before.
I threw a little deployment of this PR on https://lg.clint64.net/search/livegrep, feel free to poke around. (Your browser can simulate light/dark mode preferences with the dev tools -- in Chrome, open the "Rendering" tool (probably hit Escape to open that extra tool drawer??), in Firefox these are icons in a sidebar of the "Inspector" pane.)
I'm not at all tied to any particular colors here, and I may have missed some places that need additional styling! …
=> Support darkmode with CSS media query

web/src/codesearch/codesearch_ui.js
Hello, this PR allow to click on the query hint to add it to the search and then focus on the search input to complete the query hint.
=> Allow to click on query hint

WORKSPACE, server/backend.go, server/config/config.go, server/server.go
Fixes #360.
I deployed this change and with the corresponding flag to `codesearch` was actually able to see larger responses in the frontend. (Something like `max_matches:3000` is enough to hit the limit for the query I ran.)
The `WORKSPACE` change is just to silence a warning.
=> Allow Go server config to specify grpc dial opts

server/config/config.go, web/src/codesearch/codesearch_ui.js
We want to set `target="_blank"` on some file links.
=> Allow setting 'target' attr on link configs

doc/examples/livegrep/server.json, server/config/config.go, server/fileview.go, server/server.go, web/templates/fileview.html
I've _long_ wanted a way to add new file extensions without a PR, merge, build dance -- finally got around to adding it.
The specific motivation was terraform `.tf` files, which a newer version of PrismJS includes (as generic HCL, Hashicorp configuration language). I updated the example, though maybe we do want that as a default inclusion too.
Edit: I threw another small commit here to use a regex on the first line too -- we often have small shell (and Ruby of course 🙂) scripts that have no extension, but nevertheless would be much nicer to have highlighted:
`bin/groups-graph`:
=> Add config option for file extension, language mapping

docker/base/Dockerfile, server/server.go
The base image currently only spits out "Error reading file". Adding git to the image fixes the issue.
=> Include git in base dockerfile

docker/base/Dockerfile, docker/nginx/Dockerfile
I think #371 broke the CI because APT is waiting for input and the build times-out. 
[Reference](https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai)
I tested it on my fork and it seems to work, [see here.](https://github.com/mucinoab/livegrep/actions/runs/5481686560
)
=> Fix CI: Disable the interactive dialogue in APT

web/src/codesearch/repo_selector.js
In recently added repos grouping feature bug was detected. After selecting a number of repos using group header, search results weren't updating. Small fix for this problem here.
=> Fix search update loss, when selecting repos using group header.

.bazelrc, .bazelrc.ci, .vscode/settings.json, BUILD, WORKSPACE, server/api.go, server/query.go, server/query_test.go, src/codesearch.cc, src/codesearch.h, src/proto/livegrep.proto, src/tagsearch.cc, src/tools/grpc_server.cc, test/codesearch_test.cc, test/tagsearch_test.cc, tools/gopackagesdriver.sh
This PR fixes #378.
(This is probably easiest to review commit-by-commit. The first one was necessary to get anything building on the Macs I have access to, and the second isn't necessary but makes editing Bazel-y C++ and Go much more pleasant.)
Changing the `Query` proto to accept a repeated `file` (or `not_file`) is straightforward, with one slightly odd caveat. `FilenameOnly` queries did not make use of the `file` field but, for some reason, repurposed `line`. This is still true, but the `line` pattern is used as the "most important" one, since we don't support multiple bounds in a match (see https://github.com/livegrep/livegrep/pull/349).
The changes to _use_ the additional values are mostly boring loops where previously one check sufficed. The tagsearch changes might just be …
=> Support queries with multiple path: terms

src/fs_indexer.cc
Suggested fix for livegrep/livegrep#364
=> skip directories with insufficient permissions

src/fs_indexer.cc, src/fs_indexer.h, src/proto/config.proto, src/tools/codesearch.cc
Add an option to ignore symbolic links, off by default.
Some projects contain infinite symlink loops ([Example](https://github.com/jbruchon/jdupes/tree/master/testdir/recursed_a)) or symlinks that point outside the directory tree. The former just slows down indexing because the recursion stops after a certain maximum depth, while the latter can be a security issue in certain setups.
There are workarounds that don't require changing livegrep, such as a [filtering read-only FUSE](https://github.com/wfrisch/rofs-filtered), but IMHO it would be more comfortable to just have this option in livegrep itself.
=> ignore_symlinks option

web/templates/common/layout.html
This PR removes the Stripe keyword from the `<link rel=search>` tag for `opensearch.xml`.
=> Remove Stripe brand from opensearch.xml

web/templates/common/layout.html
Livegrep is still with the Google Analytics 3 mechanism of collecting data from the website according to the customer's ID. Since Google Analytics 4 was launched and the previous was deprecated, the data is not being collected properly. We must add the new method provided by GA platform in order to have analytics data being collected properly and sent to the customer's Google Analytics dashboard.
I noticed that Livegrep uses Google Tag Manager instead of the basic method provided by Google Analytics 4. After some research, I found this [blog post](https://www.analyticsmania.com/post/how-to-install-google-tag-manager/) where we can identify that method provided by Google Tag Manager.
First, we have to change the previous implemented function inside the `<head>` tag to the new one. Then, we …
=> Adding new GA4 tagging code snippets to common layout

web/templates/common/layout.html
This PR makes it possible to serve Livegrep content using a CSP policy that relies on hashes without using Nonce.
Previously, it was not possible to create a hash of the inline script that consumes `{{.ScriptData}}` because the data is dynamically generated and the hash is not stable. This inline script was the only `<script>` tag for which a hash cannot be computed.
With this PR, it's possible to compute the hash for the inline script because the dynamic data is stored in a harmless `application/json` block while the JS script tag has stable content.
=> Make window.scriptData initialization hashable

BUILD, WORKSPACE, cmd/BUILD, src/tools/BUILD, web/BUILD
Add `rules_pkg` to use `pkg_tar` instead of using `pkg_tar` from `bazel_tools`, as this seems to fix [issue](https://github.com/livegrep/livegrep/issues/390) I reported about build not working on Ubuntu 24.04.
Including `rules_pkg` is also required to upgrade to later versions of Bazel (Bazel 6 and higher), since it was moved into its own repository.
=> Use pkg_tar from rules_pkg

web/templates/common/layout.html
* Update Google Analytics tag to last release from Google
* Move it to first line of `<head>`
* Remove deprecated declaration of Google Analytics tag
Thanks for the changes on #386 it is now possible to use the latest version of Google Analytics [after deprecation of Universal Analytics](https://support.google.com/analytics/answer/13467533?hl=en#zippy=%2Cin-this-article).
Opening this PR to update the code for new release of Google Analytics 4, remove the deprecated code, and move declaration [immediately after the <head> element as recommended on the docs](https://support.google.com/google-ads/answer/12985952?hl=en).
=> Update Google Analytics Implementation after new release

doc/examples/livegrep/index_with_ordered_contents.json
In commit 74f24994, fields were renamed to use underscores instead of dashes, but in the ordered contents example, field `ordered-contents` wasn't updated. It now uses the same field present in `src/proto/config.proto`.
There was also a trailing comma at the end. For consistency with other examples, it was removed as well.
=> Fix ordered contents example

cmd/livegrep-github-reindex/main.go, web/src/codesearch/codesearch_ui.js
Two separate fixes, either one should suffice, and I believe both are correct.
=> Fix the broken links on livegrep.com

WORKSPACE
The result of:
```
bazel run //:gazelle -- update-repos golang.org/x/sys
```
This resolved an error of the form:
```
$ bazel build //...
[...snip...]
ERROR: /home/chromy/.cache/bazel/_bazel_chromy/ca4a0af3e2282fdc79af362ae706ecf4/external/org_golang_google_grpc/internal/syscall/BUILD.bazel:3:11: GoCompilePkg external/org_golang_google_grpc/internal/syscall/syscall.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/org_golang_google_grpc/internal/syscall/syscall_linux.go -src ... (remaining 23 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict …
```
=> Add golang.org/x/sys to WORKSPACE

cmd/livegrep-github-reindex/main.go
The error here refers to -installation-key, but the flag's name is actually -installation-token. This just fixes that up.
=> Update error to use correct flag name
