- server/config/config.go
- web/htdocs/assets/js/codesearch_ui.js
- web/templates/layout.html
The four commits below are mutually independent, so feel free to pick and choose!  See the commit messages for more detailed descriptions.
I've been testing manually.
> Custom HTML, github fi links, re-searching when backend drop-down is changed, permalinks for backends with periods in them

- web/templates/help.html
I spent 2-3 minutes looking for this, so I may as well add it to the "help" page.
> Added link to the RE2 Syntax Guide

- web/templates/layout.html
Updated script according to this page:
https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs
> Update google analytics tracking code

- doc/examples/livegrep/index.json
- server/backend.go
- server/server.go
- src/fs_indexer.cc
- src/fs_indexer.h
- src/tools/codesearch.cc
- src/tools/transport.cc
- src/tools/transport.h
- web/htdocs/assets/js/codesearch_ui.js
- web/templates/index.html
Addresses #21 
This does break existing config files containing fs_paths - not sure if that's okay. I tried to maintain compatibility for the github metadata, which I figured is probably more important. Also, maybe there should be a better name other than fs_paths.
> Add repo support for other VCS through fs_paths

- cmd/livegrep-github-reindex/main.go
GitHub Enterprise interactions work essentially the same as those with
the GitHub public API, but with a different API base URL.  Happily,
`go-github` already supports this; we just need a flag to allow users
to point the indexer at their GitHub Enterprise base URL.
> livegrep-github-reindex: support GitHub enterprise

- WORKSPACE
- server/BUILD
- web/BUILD
A few changes I found necessary in deploying this.
> Bazel fixes

- server/api.go
- server/config/config.go
- server/query.go
- server/query_test.go
- src/codesearch.cc
- src/codesearch.h
- src/proto/livegrep.proto
- src/tools/grpc_server.cc
- test/codesearch_test.cc
> Support end-user-configurable soft-limit on number of match results

- cmd/livegrep-fetch-reindex/main.go
I accidentally included this in #50.
> Clean up stray debugging cruft

- cmd/livegrep-fetch-reindex/main.go
- cmd/livegrep-github-reindex/main.go
> Handle `codesearch` consistently in the indexers

- cmd/livegrep-fetch-reindex/BUILD
- cmd/livegrep-fetch-reindex/main.go
- src/chunk.h
- src/codesearch.cc
- src/proto/livegrep.proto
- src/tools/codesearch.cc
- src/tools/grpc_server.cc
- src/tools/grpc_server.h
- test/codesearch_test.cc
This allows the reindexing process to notify the server that it should read in the fresh index.
> Add Reload RPC

- src/tools/grpc_server.cc
- test/codesearch_test.cc
> Decouple file/repo/tag case sensitivity from line case sensitivity

- web/htdocs/assets/js/codesearch_ui.js
Duplicates check from the other result handle_* functions.
Fixes #38
> Fix case where 'displaying' search ID can decrease

- web/htdocs/assets/js/codesearch_ui.js
> Fix handling of legacy file and repo query parameters

- web/htdocs/assets/css/codesearch.css
- web/htdocs/assets/js/codesearch_ui.js
- web/templates/index.html
Partially addresses #57: this yields a much denser view, without increasing the number of results.
> Add UI control to hide result context

- web/htdocs/assets/js/codesearch_ui.js
As @alexmv noted, I left this out of #92. It turns out to be a bit more
wiring, but not *too* tricky.
After this, search URLs are becoming quite clunky, so I'll try to follow
this up with a change that only includes non-default query params.
> Pin context control state in URL

- server/query.go
- server/query_test.go
- src/codesearch.cc
- src/codesearch.h
- src/proto/livegrep.proto
- src/tools/grpc_server.cc
- test/codesearch_test.cc
Similar to #91, but we plumb through to the backend.
> Handle filename-only queries

- web/templates/index.html
Small request from users during our demo. 
They said it would be good to know searching using file: was possible and recommended adding it to the hints.
> Added file hint to index.html

- src/tagsearch.cc
Since the identifier field and filename field in a tags file cannot
contain tabs, our regular expressions that match those fields should
avoid trying to eat tabs.  The actual chance of a mismatch is small, but
this tiny bit of extra correctness should also give the patterns the
best possible chance of running quickly.
> Stop tag file regular expressions from eating tabs

- .bazelrc.circle
- .circleci/Dockerfile
- WORKSPACE
- client/test/BUILD
- src/tools/BUILD
- test/BUILD
- tools/build_defs/go_externals.bzl
I'll bump CI once I'm at a laptop with my gcloud credentials.
> Upgrade dependencies to make bazel 0.6 happy

- .circleci/build.sh
- .circleci/config.yml
this will hopefully fix builds on PRs
> circle: only upload packages if we have credentials

- src/tools/codesearch.cc
> Use a unique_ptr

- web/src/fileview/fileview.js
When a user highlights a search term in the file viewer and presses `/`
to search, we currently forget what repositories they were searching
earlier and widen back out to a search of all repositories.  Until we
can do something more sophisticated, let’s at least restrict the search
they create with `/` to the repository of the file they’re viewing.
> Search in repo when initiated from a file view (#6)

- web/htdocs/assets/css/codesearch.css
- web/src/codesearch/codesearch_ui.js
- web/templates/index.html
Another popular request from among our most dedicated Livegrep users!
This duplicates a bit of code from `fileview.js` but as it looked like
the two have been kept separate so far, I didn't choose this diff as the
moment to create a common module where the shared code could live.
> Let '/' search for selected text on main page

- web/templates/index.html
This helps with discoverability and ease of use.
> Add max_matches as a query hint

- src/BUILD
- src/chunk.cc
- src/chunk.h
- src/chunk_allocator.cc
- src/codesearch.cc
- src/codesearch.h
- src/dump_load.cc
- src/tagsearch.cc
- src/tools/codesearch.cc
- src/tools/dump-file.cc
- test/codesearch_test.cc
> Port a lot of storage to unique_ptr and vector

- WORKSPACE
> Bump rules_node

- src/tools/grpc_server.cc
- test/codesearch_test.cc
Add a test, and add a test for the "filtering from matches" logic,
too.
fixes #185
> Filter invalid UTF-8 from context.

- src/tagsearch.cc
- src/tools/grpc_server.cc
Before we were highlighting the entire symbol returned from a tags
search, but now we’ll just highlight the actual search term for the
frequent cases where the user has typed only a prefix of the symbol.
> Correctly highlight lines from tags matches

- server/server.go
- web/src/fileview/fileview.js
And consume it from javascript instead of parsing the URL
> Pass file_path to scriptData

- src/codesearch.cc
- src/query_planner.cc
- src/query_planner.h
- src/tools/analyze-re.cc
- src/tools/dump-file.cc
- test/BUILD
- test/planner_test.cc
I've been calling it this verbally and in tech talks, and I think it's a better name.
> Rename the "indexer" to the "query planner"

- cmd/livegrep-github-reindex/main.go
> livegrep-github-index: Update HEAD as well as other refs

- cmd/livegrep-github-reindex/main.go
> Pass the github key to the git fetch or clone, if given

- WORKSPACE
> Bump rules_node for bazel compatibility

- .circleci/Dockerfile
- .circleci/config.yml
- README.md
- WORKSPACE
Pull in #231 to make it build.
> Bump bazel in CI

- src/proto/config.proto
Implementation of the proposal documented in #248.
> proto: Add labels to metadata message

- src/tools/codesearch.cc
This allows disabling SO_REUSEPORT, so that subsequent concurrent
server instances running on the same port will exit with an error,
instead of load-balancing with the existing one.
Fixes #262
> Add a -reuseport option

- cmd/livegrep-github-reindex/main.go
We need to use `x-access-token:<token>` as out HTTP credentials.
fixes #269
> Support cloning using github application keys

- cmd/livegrep-fetch-reindex/BUILD
- cmd/livegrep-fetch-reindex/main.go
- cmd/livegrep-github-reindex/BUILD
- cmd/livegrep-github-reindex/main.go
- src/proto/config.proto
This is basically an implementation of https://github.com/livegrep/livegrep/pull/235#issuecomment-627760971 from #235
> Refactor the indexer scripts to reduce duplication

- README.md
> Bump Bazel version in README

- tools/org_dropbox_rules_node/node/tools/npm/utils.py
> make utils.py python3 compatible

- tools/org_dropbox_rules_node/node/defs.bzl
Quick and kinda dirty fix for #296.
The "error" appeared to be python related, but it was actually a failure from the python wrapper trying to run the linux binary on a Mac.
This could probably use some refinement, notably we don't _fail_ if you're on Windows, darwin-arm64, etc.
> Support nodejs on darwin-x64 and linux-x64

- src/dump_load.cc
[`mmap(2)`](https://linux.die.net/man/2/mmap) on Linux recognizes the `MAP_POPULATE` flag which eagerly prefaults the memory-mapped region into virtual memory, which reduces the rate of page misses during I/O on the memory-mapped file.
This change:
* Adds a flag `--eager_memory_load` to opt-in to eager prefaulting, supported only on Linux.
* Changes the existing `MAP_SHARED` flag to `MAP_PRIVATE`. Use of `MAP_POPULATE` requires `MAP_PRIVATE` on Linux. `MAP_SHARED` allows the memory-mapped region to be visible to other processes, but as far as I can tell this is not actually useful for livegrep since the index file data is only consumed exclusively by the codesearch process.
In livegrep, enabling eager memory load on the code search index tangibly reduces average search query latency due …
> dump_load: Option for eager mmap prefault with MAP_POPULATE on Linux

- src/dump_load.cc
- src/dump_load.h
> Fix M1 support by using a larger page size

- README.md
> Some doc updates

- README.md
> Correct path to run livegrep

- README.md
- Update CI badge
- Update `master` to `main`
> Fix a few references in the README

- server/server.go
The list of repo URLs is useful to have exposed outside the templated HTML, along with any custom link configs: I'm poking at some experimental frontend/CLI changes and it would be helpful to have access to this configuration.
We only have one backend -- I'm not sure how widely used multiple backends are? Would that be potentially useful too?
(I _think_ something similar was done in the changes discussed in #326 but that wasn't upstreamed and I'm not seeing any [similar routes in their current fork](https://github.com/xvandish/livegrep/blob/my_main/server/server.go#L607).)
> Expose search page configuration in API endpoint

- src/git_indexer.cc
This PR should fix a `codesearch` crash in the rare (?) event that a git tree entry fails to convert to a git object for further analysis in the `walk_tree` logic path, by ensuring that `git_tree_entry_to_object` returns `0` before extracting the object contents.
This fixes the following crash I encountered while indexing a large repository:
```
codesearch: external/com_github_libgit2/src/object.c:219: git_object_type: Assertion `obj' failed.
```
I didn't investigate the underlying root cause of the error. It could be due to a corrupted git tree, or a tree entry unrecognized by the current version of libgit2, or something else.
Manual verification, doing offline indexing of several repositories:
```
...
Walking repo_spec name=private/repo, …
```
> git_indexer: Gracefully handle git tree entries that cannot be converted to objects
